"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Brand } from "./Brand";

export function AdminLogin() {
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter();
  async function submit(e){e.preventDefault(); setBusy(true); setError(""); const data=Object.fromEntries(new FormData(e.currentTarget)); const res=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}); if(res.ok) router.refresh(); else {setError("Email or password is incorrect.");setBusy(false);}}
  return <main className="admin-login"><section><Brand/><p className="eyebrow">COURSE OPERATIONS</p><h1>Welcome back.</h1><p>Manage courses, learner progress and activity responses from one focused workspace.</p></section><form onSubmit={submit}><h2>Owner sign in</h2><label>Email address<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in →"}</button>{error&&<p className="form-error">{error}</p>}<small>Private access for the Credit Pulse team.</small></form></main>;
}

export function AdminDashboard({ course }) {
  const [tab,setTab]=useState("Overview"); const [submissions,setSubmissions]=useState([]); const [query,setQuery]=useState(""); const router=useRouter();
  useEffect(()=>{
    requestAnimationFrame(()=>{try{setSubmissions(JSON.parse(localStorage.getItem("cp-course-1-submissions"))||[])}catch{}});
  },[]);
  const filtered=submissions.filter(s=>(s.name+s.email+s.lessonTitle).toLowerCase().includes(query.toLowerCase()));
  async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.refresh()}
  function exportCsv(){const head=["Name","Email","Lesson","Response","Submitted at"];const rows=submissions.map(s=>[s.name,s.email,s.lessonTitle,s.response,s.submittedAt]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v||"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="credit-pulse-submissions.csv";a.click();}
  return <div className="admin-app"><aside className="admin-side"><Brand light/><nav>{["Overview","Courses","Submissions","Settings"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav><button onClick={logout}>Sign out</button></aside><main className="admin-main"><header><div><p className="eyebrow">CREDIT PULSE ADMIN</p><h1>{tab}</h1></div><div className="admin-avatar">RO</div></header>
    {tab==="Overview"&&<><section className="stat-grid"><article><span>Published courses</span><b>1</b><small>Course 1.1 is active</small></article><article><span>Activity submissions</span><b>{submissions.length}</b><small>Saved in this prototype</small></article><article><span>Learners observed</span><b>{new Set(submissions.map(x=>x.email)).size}</b><small>Unique email addresses</small></article></section><section className="admin-panel"><div className="panel-title"><div><p className="eyebrow">SYSTEM READINESS</p><h2>What works now</h2></div></div><div className="readiness"><article><span>✓</span><div><b>Course and admin password gates</b><p>Protected with signed, server-issued cookies.</p></div></article><article><span>✓</span><div><b>Single-page course check-in</b><p>One activity records completion for the full course.</p></div></article><article className="pending"><span>2</span><div><b>Production database and email</b><p>Connect before real learners arrive.</p></div></article></div></section></>}
    {tab==="Courses"&&<section className="admin-panel"><div className="panel-title"><div><p className="eyebrow">PUBLISHED COURSE</p><h2>{course.title}</h2></div><a className="secondary" href="/course/understanding-canadian-credit-scores" target="_blank">Open learner view ↗</a></div><div className="course-row"><div className="course-thumb">1.1</div><div><b>One continuous course</b><p>Single-link, single-password delivery</p></div><span className="status">Published</span></div></section>}
    {tab==="Submissions"&&<section className="admin-panel"><div className="panel-title"><div><p className="eyebrow">LEARNER ACTIVITY</p><h2>Activity responses</h2></div><button className="secondary" onClick={exportCsv} disabled={!submissions.length}>Export CSV</button></div><input className="search" placeholder="Search name, email or lesson…" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.length?<div className="table-wrap"><table><thead><tr><th>Learner</th><th>Lesson</th><th>Response</th><th>Submitted</th></tr></thead><tbody>{filtered.map((s,i)=><tr key={`${s.submittedAt}-${i}`}><td><b>{s.name}</b><small>{s.email}</small></td><td>{String(s.lesson).padStart(2,"0")} · {s.lessonTitle}</td><td>{s.response}</td><td>{new Date(s.submittedAt).toLocaleDateString("en-CA")}</td></tr>)}</tbody></table></div>:<div className="empty"><b>No activity responses yet</b><p>Prototype responses from this browser will appear here.</p></div>}</section>}
    {tab==="Settings"&&<section className="admin-panel settings"><p className="eyebrow">LAUNCH CHECKLIST</p><h2>Production connections</h2><div><article><b>Course access</b><span className="status">Ready</span><p>Set the course password in Vercel environment variables.</p></article><article><b>Learner data</b><span className="status pending-tag">Connect</span><p>Add Supabase or Neon so submissions sync across devices.</p></article><article><b>Email notifications</b><span className="status pending-tag">Connect</span><p>Add Resend after the database so every activity can notify your team.</p></article></div></section>}
  </main></div>;
}
