"use client";
import{useEffect,useState}from"react";
import{ArrowRight,Award,BookOpen,Calculator,Check,CheckCircle2,ChevronDown,ClipboardList,Coins,FileCheck2,Lightbulb,Menu,ReceiptText,Sparkles,WalletCards,X}from"lucide-react";
import{Brand}from"./Brand";
import{goldCourse13Glossary,goldCourse13Sections}from"../lib/gold-course-1-3-data";

const learnerKey="cp-gold-1-3-learner",completionKey="cp-gold-1-3-complete",submissionKey="cp-gold-1-3-submissions";
const outcomes=["Separate working income from adjusted net income figures.","Screen the main eligibility conditions without declaring an outcome.","Explain the basic amount, disability supplement and advance payments.","Reconcile an RC210 statement with the annual claim.","Complete a CWB and ACWB Review Sheet."];
const numbers=[["WORKING INCOME","Employment and eligible self-employment amounts enter the CWB calculation. It is not simply the money left after payday."],["ADJUSTED NET INCOME","The calculation uses adjusted net income for an individual, or adjusted family net income when a spouse or common-law partner is involved."],["BASIC CWB","The benefit rises from zero as working income begins, reaches a maximum, then is reduced as adjusted income passes the applicable threshold."],["DISABILITY SUPPLEMENT","An additional amount may be available when the person is approved for the Disability Tax Credit and the relevant income conditions are met."]];
const checks=[["What are the two possible parts of the CWB?","A basic amount and a disability supplement."],["Why can gross pay and adjusted net income lead to different conclusions?","Gross pay is not the entire formula. Working income, adjusted income, family status, thresholds and provincial rules can differ."],["What is ACWB, and must a worker apply separately for it?","ACWB automatically advances up to half of an estimated CWB entitlement when CRA records show entitlement; there is no separate application."],["Why should an RC210 be saved?","It records advance amounts, including any disability portion, that must be reported and reconciled on Schedule 6."],["Which locations require special attention to adjusted CWB rules?","Alberta, Quebec and Nunavut."]];
const fields=[[11,"year","My tax year, province or territory and family status are:"],[12,"income","My working-income sources and rounded total are:"],[13,"adjusted","My rounded adjusted net income or adjusted family net income is:"],[14,"eligibility","The eligibility questions I still need to verify—age, residency, student, dependant or confinement—are:"],[15,"thresholds","The current maximums, thresholds and official source date I used are:"],[16,"dtc","My DTC approval and possible disability-supplement question are:"],[17,"advances","My ACWB deposits and RC210 amounts to reconcile are:"],[18,"followup","My filing, correction or CRA follow-up step—and completion date—is:"]];

function Spot({children}){return <aside className="reader-spotlight gold-spotlight"><Lightbulb/><div><strong>Credit Pulse spotlight</strong><p>{children}</p></div></aside>}
function Source({href,children}){return <a className="reader-source" href={href} target="_blank" rel="noreferrer">{children}<ArrowRight size={14}/></a>}
function Heading({number,title}){return <div className="reader-section-heading gold-heading"><span>{number}</span><div><h2>{title}</h2></div></div>}
function Myth({children,reality}){return <article><span>MYTH CHECK</span><p>“{children}”</p><div><CheckCircle2/>{reality}</div></article>}

export function CanadaWorkersBenefitCourse({course}){
  const[active,setActive]=useState("start"),[menu,setMenu]=useState(false),[progress,setProgress]=useState(0),[learner,setLearner]=useState({name:"",email:""}),[complete,setComplete]=useState(false);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{try{setLearner(JSON.parse(localStorage.getItem(learnerKey))||{name:"",email:""});setComplete(localStorage.getItem(completionKey)==="true")}catch{}}),update=()=>{const height=document.documentElement.scrollHeight-window.innerHeight;setProgress(height>0?Math.min(100,Math.round(window.scrollY/height*100)):0)},observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:"-20% 0px -65%",threshold:[0,.25,.6]});goldCourse13Sections.forEach(({id})=>{const section=document.getElementById(id);if(section)observer.observe(section)});update();window.addEventListener("scroll",update,{passive:true});return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener("scroll",update)}},[]);
  function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)}
  function submit(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),next={name:data.name,email:data.email},response=fields.map(([number,name,label])=>`${number}. ${label} ${data[name]}`).join("\n"),rows=JSON.parse(localStorage.getItem(submissionKey)||"[]");rows.unshift({...next,lesson:1.3,lessonTitle:"Gold · Canada Workers Benefit",response,submittedAt:new Date().toISOString()});localStorage.setItem(submissionKey,JSON.stringify(rows));localStorage.setItem(learnerKey,JSON.stringify(next));localStorage.setItem(completionKey,"true");setLearner(next);setComplete(true)}
  return <div className="reader-shell gold-course"><div className="reader-progress gold-progress"><span style={{width:`${progress}%`}}/></div><header className="reader-header gold-header"><button className="reader-menu-button" onClick={()=>setMenu(true)} aria-label="Open course contents"><Menu/></button><Brand/><div className="reader-header-meta"><BookOpen size={17}/><span>Gold 1.3</span><i/><span>{progress}% read</span></div><div className="gold-tier-mark"><Award/>GOLD EXCLUSIVE</div><a className="reader-help" href="mailto:support@creditpulse.ca">Need help?</a></header><aside className={`reader-nav gold-nav ${menu?"open":""}`}><div className="reader-nav-head"><div><span>GOLD 1.3</span><strong>On this page</strong></div><button onClick={()=>setMenu(false)} aria-label="Close course contents"><X/></button></div><nav>{goldCourse13Sections.map((section,index)=><button key={section.id} className={active===section.id?"active":""} onClick={()=>go(section.id)}><span>{String(index+1).padStart(2,"0")}</span>{section.label}</button>)}</nav></aside>{menu&&<button className="reader-scrim" onClick={()=>setMenu(false)} aria-label="Close course contents"/>}<main className="reader-main">
    <section className="reader-hero gold-hero" id="start"><div className="reader-hero-copy"><p className="reader-kicker">{course.eyebrow}</p><h1>{course.title}</h1><p className="reader-subtitle">{course.subtitle}</p><p className="reader-deck">Screen → Calculate → Advance → Reconcile → Act</p><div className="reader-meta"><span><Sparkles/>{course.duration}</span><span><Calculator/>One paycheque booster lab</span></div><button className="reader-primary gold-primary" onClick={()=>go("numbers")}>Run the four-number lab <ArrowRight/></button></div><div className="gold-hero-art"><div className="gold-file"><div className="gold-icon"><WalletCards/></div><span>PAYCHEQUE BOOSTER</span><strong>CWB LAB</strong><small>CALCULATE · ADVANCE · RECONCILE</small></div><div className="gold-seal"><Award/>GOLD</div></div></section>
    <div className="reader-body gold-body"><section className="reader-section reader-intro"><p className="reader-lead">A paycheque can disappear with the confidence of a magician who has rent, groceries and a phone bill helping backstage.</p><p>The Canada Workers Benefit, or CWB, is a refundable federal tax credit for eligible workers and families with low income. It has a basic amount and a possible disability supplement. The final amount is calculated through the annual income tax return; it is not a fixed bonus attached to every job.</p><Spot>For the 2025 tax year, the published maximum basic CWB is $1,633 for a single individual and $2,813 for a family. Income limits and calculations differ in Alberta, Quebec and Nunavut, and a maximum is never a personal quote.</Spot><div className="gold-outcomes">{outcomes.map((outcome,index)=><article key={outcome}><span><Check/></span><p>{outcome}</p><small>0{index+1}</small></article>)}</div><div className="myth-list gold-myth"><Myth reality="Work is only the opening scene. Age, residency, student or confinement rules, family situation and income calculations all matter; the maximum is the ceiling, not the welcome mat.">If I worked during the year, I automatically receive the maximum CWB.</Myth></div><div className="reader-links"><Source href="https://www.canada.ca/en/revenue-agency/services/child-family-benefits/acwb-eligibility.html">CRA: Canada Workers Benefit</Source></div></section>
    <section className="reader-section" id="numbers"><Heading number="02" title="Do Not Ask One Number to Do Four Jobs"/><div className="gold-panel-grid gold-number-grid">{numbers.map(([title,copy],index)=><article key={title}><div className="gold-icon">{index===0?<Coins/>:index===1?<ReceiptText/>:index===2?<Calculator/>:<FileCheck2/>}</div><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Spot>For 2025, the maximum disability supplement is $843. Disability Tax Credit approval is required, and income thresholds depend on location and family circumstances.</Spot><Spot>The basic CWB begins reducing after adjusted net income exceeds $26,855 for a single individual or adjusted family net income exceeds $30,639 for a family under the standard 2025 calculation. Provincial exceptions apply.</Spot><div className="myth-list gold-myth"><Myth reality="The return separates working income from adjusted income and applies family status, thresholds, reductions and provincial rules. Tax software may do the arithmetic; you should still know the ingredients.">My gross pay tells me exactly what my CWB will be.</Myth></div></section>
    <section className="reader-section" id="advance"><Heading number="03" title="Early Money Is Still Part of the Same Benefit"/><p>If CRA records show entitlement, the Advanced Canada Workers Benefit can automatically deliver up to half of the estimated CWB during the year. There is no separate ACWB application. The estimate uses tax information already filed, while the final annual CWB is settled on the next return.</p><Spot>The 2026 ACWB payment dates are 12 January, 10 July and 9 October. Dates can shift, so confirm the current schedule before building a cash-flow plan around them.</Spot><p>CRA issues an RC210 statement showing advance amounts, including any disability portion. Keep it with your tax records and report it on Schedule 6. An advance is part of the year’s benefit arriving before the final calculation.</p><Spot>Alberta, Quebec and Nunavut use adjusted CWB maximums or thresholds. Select the correct provincial or territorial Schedule 6.</Spot><div className="myth-list gold-myth"><Myth reality="They are advances against the estimated annual benefit. The return reconciles what arrived early with the final calculation, so save the RC210 and avoid counting the same dollars twice.">ACWB payments are extra money on top of the final CWB.</Myth></div><div className="gold-conclusion"><FileCheck2/><div><h3>Key takeaway</h3><p>The CWB is settled through the annual tax return. ACWB is early delivery of part of an estimated entitlement—not an extra benefit—and must be reconciled with the final claim.</p></div></div></section>
    <section className="reader-section" id="story"><Heading number="04" title="Maya and the Refund That Arrived Early"/><div className="story-card gold-story"><div className="story-content"><p className="reader-kicker">DEDICATED STORY</p><h3>Meet Maya</h3><p>Maya Singh, a Halifax line cook, had hours that changed with the season. When an ACWB deposit arrived, she assumed it was a new bonus and planned to count the same amount again in her spring refund.</p><p>The conflict appeared when her RC210 called the deposit an advance. Her income had also risen after extra shifts, so the prior-return estimate did not guarantee the same final entitlement. The money was real; the double-counting was the illusion.</p><p>Maya saved the RC210, entered the advance on Schedule 6, checked Nova Scotia figures and used a cautious estimate. Her filed return reconciled the early payments with the final calculation.</p></div></div><Spot>A changing work schedule does not make planning impossible. Keep pay records, update a rounded income estimate and reserve part of an unexpected advance until the annual calculation is clear.</Spot></section>
    <section className="reader-section" id="quick-check"><Heading number="05" title="Quick Check: Choose the Best Next Move"/><div className="quick-checks gold-checks">{checks.map(([question,answer],index)=><details key={question}><summary><span>{index+6}</span><strong>{question}</strong><ChevronDown/></summary><div><b>{answer}</b></div></details>)}</div></section>
    <section className="reader-section" id="action"><Heading number="06" title="Complete Your CWB and ACWB Review Sheet"/><p>Use rounded figures and the current CRA worksheet or certified software. Do not enter SINs, banking details or complete tax-account identifiers here.</p>{complete?<div className="reader-completion gold-completion"><span><Check/></span><h3>Review sheet complete{learner.name?`, ${learner.name.split(" ")[0]}`:""}.</h3><button className="reader-primary gold-primary" onClick={()=>window.print()}>Print review sheet <ClipboardList/></button></div>:<div className="calculator-frame checkin-form-frame gold-form-frame"><form className="checkin-form" onSubmit={submit}><div className="checkin-identity"><label>Full name<input name="name" defaultValue={learner.name} required/></label><label>Email address<input name="email" type="email" defaultValue={learner.email} required/></label></div>{fields.map(([number,name,label])=><label key={name}><span><b>{number}</b>{label}</span><textarea name={name} rows="3" required/></label>)}<label className="checkin-consent"><input type="checkbox" required/><span>I understand this is educational information, not an eligibility or payment determination.</span></label><button className="reader-primary gold-primary">Complete Gold 1.3 <ArrowRight/></button></form></div>}<Spot>Treat online estimates as planning ranges. Changes in income, marital status, DTC status or reassessment can move the final number.</Spot></section>
    <section className="reader-section reader-glossary" id="glossary"><Heading number="07" title="Glossary of Terms"/><dl>{goldCourse13Glossary.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section></div><footer className="reader-footer"><Brand light/><p>Credit education, made clear.</p><a href="#start">Back to top ↑</a></footer></main></div>
}