"use client";
import{useEffect,useState}from"react";
import{ArrowRight,Award,BookOpen,Check,CheckCircle2,ChevronDown,ClipboardList,Clock3,FileCheck2,HeartPulse,Lightbulb,Menu,NotebookPen,Sparkles,Stethoscope,UserRoundCheck,X}from"lucide-react";
import{Brand}from"./Brand";
import{goldCourse14Glossary,goldCourse14Sections}from"../lib/gold-course-1-4-data";

const learnerKey="cp-gold-1-4-learner",completionKey="cp-gold-1-4-complete",submissionKey="cp-gold-1-4-submissions";
const outcomes=["Distinguish diagnosis from functional impact.","Organize evidence around frequency, duration, time and support.","Explain the applicant, practitioner and CRA roles.","Choose a current application route.","Complete a Functional Impact Chronology and Evidence File."];
const lenses=[["FUNCTION","Describe the basic activity affected and what happens in ordinary life."],["FREQUENCY","Record how often the restriction occurs, including the pattern across better and harder days."],["TIME","Explain the time required compared with a person of similar age, where that test applies."],["SUPPORT","List therapy, medication, devices, prompting, supervision or hands-on help already used."],["DURATION","Identify when the pattern began and whether it has lasted or is expected to last at least 12 continuous months."]];
const roles=[["APPLICANT","Completes Part A, identifies who may claim the amount and provides consent. The applicant can start online and give the practitioner a reference number."],["MEDICAL PRACTITIONER","Completes Part B for the relevant category using professional judgment and clinical knowledge. A fee may be charged; ask in advance."],["CRA","Reviews the certification and decides whether the criteria and applicable years are met. CRA may request more information."],["AFTER THE DECISION","Read the notice carefully. Check approved years and tax instructions, or use the explanation and official review options."]];
const checks=[["Why is a diagnosis alone not enough for the DTC?","CRA decides eligibility using severe and prolonged functional effects under the legal criteria, not the diagnosis name alone."],["What five evidence lenses belong in a functional-impact record?","Function, frequency, time, support and duration."],["What does ‘all or substantially all of the time’ generally mean?","Generally at least 90% of the time."],["Who certifies the effects, and who decides eligibility?","A medical practitioner certifies the impairment and effects; CRA decides eligibility."],["Which application-version and submission cautions apply in 2026?","Use the preferred online form or latest T2201. From 8 September 2026, pre-2023 versions are not accepted; from 14 July, do not use general Submit Documents for a new application unless CRA asks."]];
const fields=[[11,"category","The activity or DTC category I need to discuss is:"],[12,"duration","The earliest date and expected or documented duration are:"],[13,"day","On a representative day, the functional effect looks like:"],[14,"frequency","The frequency and time comparison I can describe accurately are:"],[15,"support","The therapy, medication, device, prompting, supervision or help already used is:"],[16,"special","The cumulative-effect or life-sustaining-therapy question to discuss is:"],[17,"route","My practitioner discussion and current online or T2201 application route are:"],[18,"followup","My CRA decision, approved years and tax, transfer or related-program follow-up are:"]];

function Spot({children}){return <aside className="reader-spotlight gold-spotlight"><Lightbulb/><div><strong>Credit Pulse spotlight</strong><p>{children}</p></div></aside>}
function Source({href,children}){return <a className="reader-source" href={href} target="_blank" rel="noreferrer">{children}<ArrowRight size={14}/></a>}
function Heading({number,title}){return <div className="reader-section-heading gold-heading"><span>{number}</span><div><h2>{title}</h2></div></div>}
function Myth({children,reality}){return <article><span>MYTH CHECK</span><p>“{children}”</p><div><CheckCircle2/>{reality}</div></article>}

export function DisabilityTaxCreditCourse({course}){
  const[active,setActive]=useState("start"),[menu,setMenu]=useState(false),[progress,setProgress]=useState(0),[learner,setLearner]=useState({name:"",email:""}),[complete,setComplete]=useState(false);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{try{setLearner(JSON.parse(localStorage.getItem(learnerKey))||{name:"",email:""});setComplete(localStorage.getItem(completionKey)==="true")}catch{}}),update=()=>{const height=document.documentElement.scrollHeight-window.innerHeight;setProgress(height>0?Math.min(100,Math.round(window.scrollY/height*100)):0)},observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:"-20% 0px -65%",threshold:[0,.25,.6]});goldCourse14Sections.forEach(({id})=>{const section=document.getElementById(id);if(section)observer.observe(section)});update();window.addEventListener("scroll",update,{passive:true});return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener("scroll",update)}},[]);
  function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)}
  function submit(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),next={name:data.name,email:data.email},response=fields.map(([number,name,label])=>`${number}. ${label} ${data[name]}`).join("\n"),rows=JSON.parse(localStorage.getItem(submissionKey)||"[]");rows.unshift({...next,lesson:1.4,lessonTitle:"Gold · Disability Tax Credit",response,submittedAt:new Date().toISOString()});localStorage.setItem(submissionKey,JSON.stringify(rows));localStorage.setItem(learnerKey,JSON.stringify(next));localStorage.setItem(completionKey,"true");setLearner(next);setComplete(true)}
  return <div className="reader-shell gold-course"><div className="reader-progress gold-progress"><span style={{width:`${progress}%`}}/></div><header className="reader-header gold-header"><button className="reader-menu-button" onClick={()=>setMenu(true)} aria-label="Open course contents"><Menu/></button><Brand/><div className="reader-header-meta"><BookOpen size={17}/><span>Gold 1.4</span><i/><span>{progress}% read</span></div><div className="gold-tier-mark"><Award/>GOLD EXCLUSIVE</div><a className="reader-help" href="mailto:support@creditpulse.ca">Need help?</a></header><aside className={`reader-nav gold-nav ${menu?"open":""}`}><div className="reader-nav-head"><div><span>GOLD 1.4</span><strong>On this page</strong></div><button onClick={()=>setMenu(false)} aria-label="Close course contents"><X/></button></div><nav>{goldCourse14Sections.map((section,index)=><button key={section.id} className={active===section.id?"active":""} onClick={()=>go(section.id)}><span>{String(index+1).padStart(2,"0")}</span>{section.label}</button>)}</nav></aside>{menu&&<button className="reader-scrim" onClick={()=>setMenu(false)} aria-label="Close course contents"/>}<main className="reader-main">
    <section className="reader-hero gold-hero" id="start"><div className="reader-hero-copy"><p className="reader-kicker">{course.eyebrow}</p><h1>{course.title}</h1><p className="reader-subtitle">{course.subtitle}</p><p className="reader-deck">Observe → Record → Certify → Apply → Follow Up</p><div className="reader-meta"><span><Sparkles/>{course.duration}</span><span><NotebookPen/>One evidence studio</span></div><button className="reader-primary gold-primary" onClick={()=>go("evidence")}>Build the evidence file <ArrowRight/></button></div><div className="gold-hero-art"><div className="gold-file"><div className="gold-icon"><HeartPulse/></div><span>FUNCTIONAL IMPACT</span><strong>EVIDENCE FILE</strong><small>OBSERVE · RECORD · CERTIFY</small></div><div className="gold-seal"><Award/>GOLD</div></div></section>
    <div className="reader-body gold-body"><section className="reader-section reader-intro"><p className="reader-lead">A diagnosis may be one line long. A Tuesday involving medication, supervision, recovery time and twelve careful steps is rarely so considerate.</p><p>The Disability Tax Credit, or DTC, is a non-refundable tax credit that can reduce income tax for an approved person or, in some situations, a supporting family member. It recognizes the effect of severe and prolonged impairments. It is not a monthly disability-income payment, and approval is not based on diagnosis alone.</p><Spot>DTC categories include walking, speaking, hearing, vision, feeding, dressing, eliminating and mental functions necessary for everyday life. Life-sustaining therapy and cumulative effects have separate routes.</Spot><div className="gold-outcomes">{outcomes.map((outcome,index)=><article key={outcome}><span><Check/></span><p>{outcome}</p><small>0{index+1}</small></article>)}</div><div className="myth-list gold-myth"><Myth reality="DTC categories include physical, sensory and mental functions. The test is the certified functional effect under the law—not whether a stranger can spot the impairment.">Only visible or physical disabilities can qualify.</Myth></div><div className="reader-links"><Source href="https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit.html">CRA: Disability Tax Credit</Source></div></section>
    <section className="reader-section" id="evidence"><Heading number="02" title="Show the Pattern, Not Just the Label"/><p>A marked restriction generally means a person is unable to perform an activity, or takes about three times as long as a person of similar age without the impairment, even with appropriate therapy, devices and medication. It must be present all or substantially all of the time—generally at least 90%—and last, or be expected to last, continuously for at least 12 months.</p><div className="gold-panel-grid gold-evidence-grid">{lenses.map(([title,copy],index)=><article key={title}><div className="gold-icon">{index===0?<HeartPulse/>:index===1?<Clock3/>:index===2?<Clock3/>:index===3?<Stethoscope/>:<NotebookPen/>}</div><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Spot>Two or more significant limitations can sometimes combine into the equivalent of a marked restriction. Each limitation must meet CRA’s cumulative-effect conditions; minor inconveniences do not become eligibility by committee.</Spot><Spot>For qualifying life-sustaining therapy, the test focuses on purpose, frequency and time rules. People with type 1 diabetes are deemed to meet the therapy criterion for 2021 and later years.</Spot><div className="myth-list gold-myth"><Myth reality="A practitioner certifies the impairment and effects, but CRA decides eligibility using the legal criteria. Specific, truthful functional detail is more useful than a diagnosis name travelling alone.">A medical diagnosis guarantees DTC approval.</Myth></div></section>
    <section className="reader-section" id="route"><Heading number="03" title="Give Each Person the Correct Job"/><div className="gold-panel-grid gold-role-grid">{roles.map(([title,copy],index)=><article key={title}><div className="gold-icon">{index===0?<UserRoundCheck/>:index===1?<Stethoscope/>:<FileCheck2/>}</div><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Spot>CRA’s online DTC form is the preferred current route. For paper, use the latest T2201. From 8 September 2026, versions issued before 2023 are no longer accepted.</Spot><Spot>From 14 July 2026, do not use CRA’s general Submit Documents service for a new DTC application unless CRA specifically asks for additional information.</Spot><div className="myth-list gold-myth"><Myth reality="Unused amounts may sometimes be claimed by an eligible supporting family member, and approval can be relevant to other programs. Each claim and program has its own conditions.">A non-refundable credit is useless if the approved person owes no tax.</Myth></div><div className="gold-conclusion"><FileCheck2/><div><h3>Key takeaway</h3><p>DTC eligibility turns on severe and prolonged functional effects—not diagnosis alone. Build specific, truthful evidence, let the practitioner certify within their role and let CRA decide.</p></div></div></section>
    <section className="reader-section" id="story"><Heading number="04" title="Leah and the Form That Did Not Know Tuesday"/><div className="story-card gold-story"><div className="story-content"><p className="reader-kicker">DEDICATED STORY</p><h3>Meet Leah</h3><p>Leah Cardinal in Winnipeg had a well-documented diagnosis. Her first DTC draft repeated its name three times but said little about daily function. The diagnosis knew who it was; the form still did not know Tuesday.</p><p>She had described her hardest day as if it happened every day, then left out the supports that made other days possible. Her nurse practitioner needed an accurate pattern: frequency, duration, time, prompting, treatment and effect on basic activities.</p><p>Leah built a short chronology using appointment notes, a two-week routine log and ordinary-task examples. She recorded better and difficult days and brought questions—not a prewritten medical conclusion—to her practitioner.</p><p>The practitioner certified using clinical judgment, and CRA made the decision. The application now told one consistent, truthful story.</p></div></div><Spot>A brief diary can reveal a pattern that memory compresses. Record representative days, supports and time demands; do not exaggerate, minimize or coach a practitioner toward a predetermined answer.</Spot><p><strong>Studio note:</strong> humour belongs with the paperwork, never with a person’s disability, pain or need for support.</p></section>
    <section className="reader-section" id="quick-check"><Heading number="05" title="Quick Check: Choose the Best Next Move"/><div className="quick-checks gold-checks">{checks.map(([question,answer],index)=><details key={question}><summary><span>{index+6}</span><strong>{question}</strong><ChevronDown/></summary><div><b>{answer}</b></div></details>)}</div></section>
    <section className="reader-section" id="action"><Heading number="06" title="Complete Your Functional Impact Chronology and Evidence File"/><p>Use plain, factual language. Do not place a health card number, SIN, complete medical record or practitioner login information in this workbook.</p>{complete?<div className="reader-completion gold-completion"><span><Check/></span><h3>Evidence file complete{learner.name?`, ${learner.name.split(" ")[0]}`:""}.</h3><button className="reader-primary gold-primary" onClick={()=>window.print()}>Print evidence file <ClipboardList/></button></div>:<div className="calculator-frame checkin-form-frame gold-form-frame"><form className="checkin-form" onSubmit={submit}><div className="checkin-identity"><label>Full name<input name="name" defaultValue={learner.name} required/></label><label>Email address<input name="email" type="email" defaultValue={learner.email} required/></label></div>{fields.map(([number,name,label])=><label key={name}><span><b>{number}</b>{label}</span><textarea name={name} rows="3" required/></label>)}<label className="checkin-consent"><input type="checkbox" required/><span>I understand this is educational information, not an eligibility or tax determination.</span></label><button className="reader-primary gold-primary">Complete Gold 1.4 <ArrowRight/></button></form></div>}<Spot>Keep copies of the application, reference number, practitioner submission and CRA notice. A tidy evidence file cannot decide eligibility, but it can prevent avoidable paperwork confusion.</Spot></section>
    <section className="reader-section reader-glossary" id="glossary"><Heading number="07" title="Glossary of Terms"/><dl>{goldCourse14Glossary.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section></div><footer className="reader-footer"><Brand light/><p>Credit education, made clear.</p><a href="#start">Back to top ↑</a></footer></main></div>
}