"use client";
import{useEffect,useState}from"react";
import{ArrowRight,Award,BookOpen,CalendarClock,Check,CheckCircle2,ChevronDown,ClipboardList,FileCheck2,Globe2,Lightbulb,Map,Menu,Sparkles,TimerReset,X}from"lucide-react";
import{Brand}from"./Brand";
import{goldCourse16Glossary,goldCourse16Sections}from"../lib/gold-course-1-6-data";

const learnerKey="cp-gold-1-6-learner",completionKey="cp-gold-1-6-complete",submissionKey="cp-gold-1-6-submissions";
const outcomes=["Trace residence in Canada after age 18.","Distinguish full and partial pension concepts.","Compare starting at 65 with delaying up to 70.","Recognize income and recovery-tax effects.","Complete an OAS Residence and Start-Date Map."];
const residence=[["LIVING IN CANADA","A person generally must be at least 65, be a Canadian citizen or legal resident when approved, and have resided in Canada for at least ten years after age 18."],["LIVING OUTSIDE CANADA","A person generally needs Canadian citizenship or legal residence immediately before leaving and at least twenty years of Canadian residence after age 18."],["FULL PENSION","Forty years of residence after age 18 generally supports a full OAS pension."],["PARTIAL PENSION","With fewer than forty qualifying years, the pension may be partial—usually qualifying years divided by 40. A partial pension generally does not become full after approval."]];
const checks=[["How does OAS differ from CPP at its foundation?","OAS is based mainly on age, legal status and residence; CPP is mainly based on employment contributions."],["What residence minimum generally applies while living in Canada?","At least ten years of Canadian residence after age 18, along with the other eligibility conditions."],["How is a partial pension commonly expressed?","Qualifying years of Canadian residence after age 18 divided by 40."],["What is the maximum increase from delaying to age 70?","36%, based on 0.6% for each month of delay up to 60 months."],["Which benefits can be unavailable while OAS is delayed?","The Guaranteed Income Supplement and a spouse’s or partner’s Allowance based on that OAS."]];
const fields=[[11,"checkpoint","My 64th birthday, intended start date and application checkpoint are:"],[12,"status","My Canadian citizenship or legal-residence status to confirm is:"],[13,"canada","My Canadian residence periods after age 18 total approximately:"],[14,"outside","My periods outside Canada and documents or agreements to investigate are:"],[15,"fraction","My tentative full or partial pension fraction—and why it is only an estimate—is:"],[16,"comparison","My start-at-65 versus delay comparison includes cash flow, tax and longevity assumptions of:"],[17,"income","My income estimate, recovery-tax checkpoint and GIS or Allowance question are:"],[18,"review","My Service Canada contact, filing reminder and annual review date are:"]];

function Spot({children}){return <aside className="reader-spotlight gold-spotlight"><Lightbulb/><div><strong>Credit Pulse spotlight</strong><p>{children}</p></div></aside>}
function Source({href,children}){return <a className="reader-source" href={href} target="_blank" rel="noreferrer">{children}<ArrowRight size={14}/></a>}
function Heading({number,title}){return <div className="reader-section-heading gold-heading"><span>{number}</span><div><h2>{title}</h2></div></div>}
function Myth({children,reality}){return <article><span>MYTH CHECK</span><p>“{children}”</p><div><CheckCircle2/>{reality}</div></article>}

export function OldAgeSecurityCourse({course}){
  const[active,setActive]=useState("start"),[menu,setMenu]=useState(false),[progress,setProgress]=useState(0),[learner,setLearner]=useState({name:"",email:""}),[complete,setComplete]=useState(false);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{try{setLearner(JSON.parse(localStorage.getItem(learnerKey))||{name:"",email:""});setComplete(localStorage.getItem(completionKey)==="true")}catch{}}),update=()=>{const height=document.documentElement.scrollHeight-window.innerHeight;setProgress(height>0?Math.min(100,Math.round(window.scrollY/height*100)):0)},observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:"-20% 0px -65%",threshold:[0,.25,.6]});goldCourse16Sections.forEach(({id})=>{const section=document.getElementById(id);if(section)observer.observe(section)});update();window.addEventListener("scroll",update,{passive:true});return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener("scroll",update)}},[]);
  function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)}
  function submit(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),next={name:data.name,email:data.email},response=fields.map(([number,name,label])=>`${number}. ${label} ${data[name]}`).join("\n"),rows=JSON.parse(localStorage.getItem(submissionKey)||"[]");rows.unshift({...next,lesson:1.6,lessonTitle:"Gold · Old Age Security",response,submittedAt:new Date().toISOString()});localStorage.setItem(submissionKey,JSON.stringify(rows));localStorage.setItem(learnerKey,JSON.stringify(next));localStorage.setItem(completionKey,"true");setLearner(next);setComplete(true)}
  return <div className="reader-shell gold-course"><div className="reader-progress gold-progress"><span style={{width:`${progress}%`}}/></div><header className="reader-header gold-header"><button className="reader-menu-button" onClick={()=>setMenu(true)} aria-label="Open course contents"><Menu/></button><Brand/><div className="gold-tier-mark"><Award/>GOLD EXCLUSIVE</div><div className="reader-header-meta"><BookOpen size={17}/><span>Canadian Benefits 1.6</span><i/><span>{progress}% read</span></div><a className="reader-help" href="mailto:support@creditpulse.ca">Need help?</a></header><aside className={`reader-nav gold-nav ${menu?"open":""}`}><div className="reader-nav-head"><div><span>GOLD 1.6</span><strong>On this page</strong></div><button onClick={()=>setMenu(false)} aria-label="Close course contents"><X/></button></div><nav>{goldCourse16Sections.map((section,index)=><button key={section.id} className={active===section.id?"active":""} onClick={()=>go(section.id)}><span>{String(index+1).padStart(2,"0")}</span>{section.label}</button>)}</nav></aside>{menu&&<button className="reader-scrim" onClick={()=>setMenu(false)} aria-label="Close course contents"/>}<main className="reader-main">
    <section className="reader-hero gold-hero" id="start"><div className="reader-hero-copy"><p className="reader-kicker">{course.eyebrow}</p><h1>{course.title}</h1><p className="reader-subtitle">{course.subtitle}</p><p className="reader-deck">Trace → Qualify → Estimate → Start → Maintain</p><div className="reader-meta"><span><Sparkles/>{course.duration}</span><span><Map/>One residence timeline</span></div><button className="reader-primary gold-primary" onClick={()=>go("residence")}>Build the timeline <ArrowRight/></button></div><div className="gold-hero-art"><div className="gold-file"><div className="gold-icon"><CalendarClock/></div><span>RETIREMENT ELIGIBILITY</span><strong>OAS TIMELINE</strong><small>TRACE · ESTIMATE · START</small></div><div className="gold-seal"><Award/>GOLD</div></div></section>
    <div className="reader-body gold-body"><section className="reader-section reader-intro"><p className="reader-lead">Retirement paperwork has an unusual talent: it asks where you lived in 1987 as though everyone keeps that answer beside the spare batteries.</p><p>Old Age Security is a taxable federal pension generally available from age 65. Unlike the Canada Pension Plan, it is based mainly on age, legal status and residence in Canada—not on employment contributions. Income can reduce or eliminate payment through the OAS recovery tax.</p><Spot>A person can qualify for OAS even if they never worked in Canada or continue working after 65. Employment history is not the contribution test; residence and income still matter.</Spot><div className="gold-outcomes">{outcomes.map((outcome,index)=><article key={outcome}><span><Check/></span><p>{outcome}</p><small>0{index+1}</small></article>)}</div><div className="myth-list gold-myth"><Myth reality="CPP is mainly contribution-based through work. OAS is residence-based and income-tested through recovery rules. They may arrive near each other, but they are not financial twins.">OAS and CPP are the same pension with two envelopes.</Myth></div><div className="reader-links"><Source href="https://www.canada.ca/en/services/benefits/publicpensions/cpp/old-age-security.html">Service Canada: Old Age Security</Source></div></section>
    <section className="reader-section" id="residence"><Heading number="02" title="Start the Clock at Age 18"/><div className="gold-panel-grid gold-role-grid">{residence.map(([title,copy],index)=><article key={title}><div className="gold-icon">{index<2?<Globe2/>:<FileCheck2/>}</div><span>0{index+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Spot>International social-security agreements or certain employment outside Canada for a Canadian employer may help a person qualify. They require individual review and documents; a passport stamp is evidence, not the entire conclusion.</Spot><Spot>Service Canada may ask for residence history since age 18. Build a month-and-year timeline using immigration records, tax files, leases, school or employment documents and travel history.</Spot><div className="myth-list gold-myth"><Myth reality="Age opens the eligibility door; residence determines whether the pension is full or partial, and income can trigger recovery. Birthday candles are not supporting documents.">Everyone who turns 65 automatically receives the full OAS amount.</Myth></div></section>
    <section className="reader-section" id="start-date"><Heading number="03" title="Starting Later Raises OAS—But Delays Other Benefits"/><p>OAS can begin at 65 or be delayed for as many as 60 months, to age 70. Each month of delay increases the pension by 0.6%, to a maximum 36% increase. There is no additional increase for waiting beyond 70.</p><p>Delaying is not automatically better. While OAS is delayed, the person cannot receive the Guaranteed Income Supplement, and a spouse or common-law partner cannot receive the Allowance based on that OAS. GIS and Allowance amounts do not earn the delay increase.</p><Spot>At July-to-September 2026 rates, the maximum OAS is $751.97 monthly for ages 65 to 74 and $827.17 for age 75 and over. Rates are reviewed quarterly and actual amounts depend on residence, age and income.</Spot><Spot>Most people receive an automatic-enrolment letter around age 64. No letter one month after the 64th birthday is a reason to contact Service Canada.</Spot><div className="myth-list gold-myth"><Myth reality="The decision also affects cash flow, longevity assumptions, taxes, GIS or Allowance access and household needs. A larger future cheque can still be wrong for a present-tense budget.">Delaying OAS is always the smartest choice because the monthly amount rises.</Myth></div><div className="gold-conclusion"><TimerReset/><div><h3>Key takeaway</h3><p>OAS planning begins with residence, not a payment estimate. Confirm qualifying years, compare starting and delaying in the full household context, then monitor income and file taxes every year.</p></div></div></section>
    <section className="reader-section" id="story"><Heading number="04" title="Elena and the Missing Seven Years"/><div className="story-card gold-story"><div className="story-content"><p className="reader-kicker">DEDICATED STORY</p><h3>Meet Elena</h3><p>At 64, Elena Rossi in Calgary received an OAS letter showing a residence history that did not match her estimate. She had lived in Italy for seven years after age 18, returned to Canada and assumed decades of tax filing would politely fill the gap.</p><p>Elena wanted to know whether an international social-security agreement could help and whether the pension would be full or partial. Her shoebox of papers offered enthusiasm but very little chronology.</p><p>She rebuilt the record month by month, gathered immigration and employment documents and contacted Service Canada. Then she compared starting at 65 with delaying, including taxes and her possible GIS position.</p><p>She ended with a documented timeline, a confirmed application route and a start-date decision built from household reality.</p></div></div><Spot>When residence history is disputed or incomplete, answer with dates and evidence. A clear timeline helps Service Canada assess the file and shows which period needs proof.</Spot><p><strong>Timeline rule:</strong> record uncertainty honestly. “Month unknown—document requested” is more useful than a precise date created by optimism.</p></section>
    <section className="reader-section" id="quick-check"><Heading number="05" title="Quick Check: Choose the Best Next Move"/><div className="quick-checks gold-checks">{checks.map(([question,answer],index)=><details key={question}><summary><span>{index+6}</span><strong>{question}</strong><ChevronDown/></summary><div><b>{answer}</b></div></details>)}</div></section>
    <section className="reader-section" id="action"><Heading number="06" title="Complete Your OAS Residence and Start-Date Map"/><p>Use month-and-year ranges and non-sensitive document labels. Do not enter SINs, passport numbers or full immigration-document numbers here.</p>{complete?<div className="reader-completion gold-completion"><span><Check/></span><h3>Residence map complete{learner.name?`, ${learner.name.split(" ")[0]}`:""}.</h3><button className="reader-primary gold-primary" onClick={()=>window.print()}>Print residence map <ClipboardList/></button></div>:<div className="calculator-frame checkin-form-frame gold-form-frame"><form className="checkin-form" onSubmit={submit}><div className="checkin-identity"><label>Full name<input name="name" defaultValue={learner.name} required/></label><label>Email address<input name="email" type="email" defaultValue={learner.email} required/></label></div>{fields.map(([number,name,label])=><label key={name}><span><b>{number}</b>{label}</span><textarea name={name} rows="3" required/></label>)}<label className="checkin-consent"><input type="checkbox" required/><span>I understand this is educational information, not an eligibility or payment determination.</span></label><button className="reader-primary gold-primary">Complete Gold 1.6 <ArrowRight/></button></form></div>}<Spot>For July 2026 to June 2027, recovery tax begins when 2025 net world income exceeds $93,454. Repayment is generally 15% of income above the threshold, up to the full OAS amount.</Spot></section>
    <section className="reader-section reader-glossary" id="glossary"><Heading number="07" title="Glossary of Terms"/><dl>{goldCourse16Glossary.map(([term,definition])=><div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl></section></div><footer className="reader-footer"><Brand light/><p>Credit education, made clear.</p><a href="#start">Back to top ↑</a></footer></main></div>
}