export const course = {
  id: "course-1",
  eyebrow: "COURSE 1.1 · CREDIT FOUNDATIONS",
  title: "Understanding Canadian Credit Scores",
  subtitle: "Your credit score is a number. It is not your personality.",
  duration: "35–45 minutes",
  lessons: [
    {
      title: "Your Credit Score Is Not a Financial Report Card",
      kicker: "Start with the right mental model",
      intro: "A credit score is a prediction tool, not a judgement of your character. It summarizes patterns in your credit file so a lender can estimate risk quickly.",
      points: ["Scores are calculated from information in your credit file.", "A lower number is not a permanent label.", "Income, savings and personal worth are not what a credit score measures."],
      tip: "Treat the score as a dashboard light: useful information, not your identity.",
      question: "In your own words, what does a credit score represent?",
      visual: "gauge",
    },
    {
      title: "What Is Inside the Number?",
      kicker: "Meet the moving parts",
      intro: "Scoring models weigh several categories of behaviour. The exact formula varies, but the habits behind the score are much less mysterious than the number can make them feel.",
      points: ["Payment behaviour has significant influence.", "Balances relative to available revolving credit matter.", "Account history, credit mix and recent applications can also contribute."],
      tip: "Build habits around the factors you can control instead of chasing a magic number.",
      question: "Which score factor do you most want to improve or understand?",
      visual: "factors",
    },
    {
      title: "Payment History: Boring, Powerful, Important",
      kicker: "Consistency does heavy lifting",
      intro: "On-time payments are one of the clearest signals a credit file can contain. Missed payments can matter, while a long pattern of paying as agreed helps tell a steadier story.",
      points: ["Know every payment due date.", "Use reminders or automatic minimum payments when appropriate.", "If you are struggling, contact the lender before ignoring the account."],
      tip: "A boring payment system is a good payment system. Make the reliable choice the easy choice.",
      question: "What one change could make your payment routine more reliable?",
      visual: "timeline",
    },
    {
      title: "Credit Utilization: The Percentage Hiding in Plain Sight",
      kicker: "A small ratio with a big role",
      intro: "Utilization compares your revolving balance with your available revolving credit. If a card has a $5,000 limit and a $1,000 balance, its utilization is 20%.",
      points: ["Both individual-card and overall utilization can be relevant.", "Lower reported balances generally present less reliance on revolving credit.", "Paying before a statement reports may change the balance that reaches a bureau."],
      tip: "Think in percentages, not just dollars. A $1,000 balance looks different on a $2,000 limit than on a $10,000 limit.",
      question: "What will you check on your revolving accounts after this lesson?",
      visual: "utilization",
    },
    {
      title: "Why You Can Have More Than One Score",
      kicker: "Different snapshots, different models",
      intro: "Canada has two major credit bureaus, Equifax and TransUnion. The information each receives can differ, and lenders may use different scoring models or versions.",
      points: ["Not every lender reports the same data to both bureaus at the same time.", "Consumer-facing scores can differ from a lender's score.", "A score difference is a reason to inspect the underlying reports, not panic."],
      tip: "Focus on report accuracy and strong habits across time rather than trying to make two scores identical.",
      question: "Why might two legitimate credit scores for the same person differ?",
      visual: "bureaus",
    },
    {
      title: "What Your Score Does Not Know About You",
      kicker: "The number has boundaries",
      intro: "A credit score is deliberately narrow. It does not contain the whole picture of your financial life, and it certainly does not contain the whole picture of you.",
      points: ["Your salary is not a scoring factor in the credit file itself.", "Your emergency fund is not the same thing as your credit history.", "Lenders can consider information beyond a credit score when making a decision."],
      tip: "Good credit and good overall finances overlap, but they are not interchangeable goals.",
      question: "Name one important part of financial health that a credit score does not capture.",
      visual: "boundaries",
    },
    {
      title: "Hard and Soft Inquiries",
      kicker: "Not every credit check is the same",
      intro: "A soft inquiry generally does not affect a credit score. A hard inquiry is associated with an application for credit and can be considered by scoring models.",
      points: ["Checking your own credit is generally a soft inquiry.", "A lender reviewing an application may create a hard inquiry.", "Apply deliberately rather than collecting applications just to see what happens."],
      tip: "Before an application, ask what kind of credit check will occur if the process is unclear.",
      question: "What is the practical difference between a hard and soft inquiry?",
      visual: "inquiries",
    },
    {
      title: "Credit Myths That Refuse to Retire",
      kicker: "Put the folklore on trial",
      intro: "Credit advice spreads easily because a simple rule sounds comforting. Unfortunately, some of the most repeated rules are incomplete or simply wrong.",
      points: ["Carrying interest-bearing debt is not required to prove you can use credit.", "Checking your own credit does not normally hurt your score.", "Closing an old card can change available credit and history—context matters."],
      tip: "When advice sounds absolute, ask what part of the credit file would actually make it true.",
      question: "Which credit myth have you heard most often?",
      visual: "myths",
    },
    {
      title: "What Changes in Your Province?",
      kicker: "Federal system, provincial context",
      intro: "The fundamentals of credit scoring are broadly Canadian, while consumer protection and credit-reporting rules can have provincial dimensions. Your next step should match where you live.",
      points: ["Start with your credit reports and verify identifying and account information.", "Keep records when disputing inaccurate information.", "Use your provincial consumer-protection resources when you need local guidance."],
      tip: "The course supports learners in AB, BC, NB, ON, NL and PEI; always confirm current local rules with the appropriate authority.",
      question: "What province are you in, and what is one local resource you can bookmark?",
      visual: "provinces",
    },
    {
      title: "Your Practical Credit Roadmap",
      kicker: "Turn understanding into a routine",
      intro: "Credit improvement is usually less dramatic than people expect. A repeatable routine—review, correct, automate, reduce and monitor—beats a burst of anxious activity.",
      points: ["Days 1–30: review reports, dates and revolving balances.", "Days 31–60: stabilize payments and work on high utilization.", "Days 61–90: re-check your system, correct remaining errors and keep applications intentional."],
      tip: "You do not need to fix everything this afternoon. Build the system you can still follow three months from now.",
      question: "What is the first action on your personal 90-day roadmap?",
      visual: "roadmap",
    },
  ],
};

export const provinces = ["Alberta", "British Columbia", "New Brunswick", "Ontario", "Newfoundland and Labrador", "Prince Edward Island"];

export const courseSections = [
  { id: "start", label: "Start here" },
  { id: "influences", label: "What influences your score" },
  { id: "myths", label: "Myths and score changes" },
  { id: "priorities", label: "The priority order" },
  { id: "rebuilding", label: "Credit rebuilding" },
  { id: "quick-check", label: "Quick check" },
  { id: "action", label: "Your action" },
  { id: "glossary", label: "Glossary" },
];

export const glossary = [
  ["Credit bureau", "A company that collects and maintains consumer credit information. Canada’s two main bureaus are Equifax and TransUnion."],
  ["Credit report", "The detailed record of your reported credit accounts and payment history."],
  ["Credit score", "A three-digit estimate of lending risk calculated from credit-report information."],
  ["Credit utilization", "How much revolving credit you are using compared with how much is available."],
  ["Minimum payment", "The smallest required payment shown on a credit statement for that billing period."],
  ["Statement balance", "The amount owed when your statement is produced."],
  ["Hard inquiry", "A credit check generally connected with applying for new credit that may affect your score."],
  ["Soft inquiry", "A credit check, such as checking your own report, that does not affect your score."],
  ["Secured credit card", "A credit card backed by money provided as security or collateral."],
  ["Revolving credit", "Credit you can borrow, repay and use again up to an approved limit, such as a credit card or line of credit."],
];
